mode: 'train'

model:
    name: 'resnet50'

data:
    fold: 3
    train_dir: './dataset/train/'
    folds_dir: './data/folds.csv'

train:
    batch_size: 50
    num_epochs: 10
    report_each: 10
    patience: 10

optimizer:
    name: 'adam'
    params:
        lr : 0.0001