mode: 'train'

model:
    name: 'resnet50'

data:
    fold: 0
    train_dir: '../iMET Collection/data/train/'
    folds_dir: './data/folds.csv'

train:
    batch_size: 50
    num_epochs: 6

optimizer:
    name: 'adam'
    params:
        lr : 0.0001