mode: 'train'

model:
    name: 'se_resnext101_32x4d'
    input_shape: 224

data:

    train_dir: './dataset/train/'
    folds_dir: './data/folds.csv'

train:
    batch_size: 64
    num_epochs: 30
    report_each: 10
    patience: 10

optimizer:
    name: 'adam'
    params:
        lr : 0.0001